getLiquidName
friendlyhj/GrassUtils pull request #3
Opened 2021-09-04 16:08 UTC by GBLodb

2021-09-04 22:56 UTC, friendlyhj commented on main/StringHelper.zs
> +    var id as string = input.definition.name;
```suggestion
    return input.definition.name;
```

2021-09-05 03:28 UTC, friendlyhj requested changes

2021-09-05 03:28 UTC, friendlyhj commented on main/StringHelper.zs
> +    return id ~ ":" ~ meta;
你改这干嘛？

2021-09-05 03:29 UTC, GBLodb commented on main/StringHelper.zs
> +    return id ~ ":" ~ meta;
草，我改过吗

2021-09-05 10:57 UTC, friendlyhj commented on main/StringHelper.zs
> +    return id;
```suggestion

```

2021-09-05 10:59 UTC, merged